services:
  frontend:
    image: nginx:1.21
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.urialfrontend.loadbalancer.server.port=80"
      - "traefik.http.routers.urialfrontend.rule=Host(`frontend.demo.app`)"
      - "traefik.http.routers.urialfrontend.entrypoints=websecure"
      - "traefik.http.routers.urialfrontend.tls.certresolver=le"
    volumes:
      - ./:/var/www/html
      - ./frontend/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    links:
      - php:php
    networks:
      - traefik-public
      - demo-private
    restart: always

  backend:
    image: nginx:1.21
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.urialbackend.loadbalancer.server.port=80"
      - "traefik.http.routers.urialbackend.rule=Host(`backend.demo.app`)"
      - "traefik.http.routers.urialbackend.entrypoints=websecure"
      - "traefik.http.routers.urialbackend.tls.certresolver=le"
    volumes:
      - ./:/var/www/html
      - ./backend/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    links:
      - php:php
    networks:
      - traefik-public
      - demo-private
    restart: always

  php:
    build: php
    volumes:
      - ./:/var/www/html
    networks:
      - demo-private

  php-cli:
    build: php-cli
    volumes:
      - ./:/var/www/html
    networks:
      - demo-private

  mariadb:
    image: mariadb:11.3.2
    environment:
      MYSQL_ROOT_PASSWORD: pippobowie
      MYSQL_DATABASE: demoapp
    ports:
      - 20904:3306
    networks:
      - demo-private
    volumes:
      - mariadbdata:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 20903:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: pippobowie
      UPLOAD_LIMIT: 300M
    networks:
      - demo-private
    restart: always

networks:
  traefik-public:
    external: true
  demo-private:
    driver: bridge

volumes:
  mariadbdata: